---
driver_plugin: ec2
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero

platforms:
- name: ec2
  driver_plugin: ec2
  driver_config:
    username: ubuntu
    image_id: <%= ENV['DEFAULT_IMAGE'] %>
    ssh_key: <%= ENV['AWS_PRIVATE_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[shell]
  attributes:
    shell:
      users:
        ubuntu:
          name: Test User
          email: test.user@example.com
